from PySide6.QtGui import QTextDocument

from configgen.ui.highlighters import ConfigHighlighter
from configgen.ui.theme import DARK, LIGHT


def _first_line_formats(text: str, palette=LIGHT) -> list[dict]:
    """Plain-Python snapshots of the first block's format ranges — the
    underlying QTextCharFormat objects don't survive the document/
    highlighter going out of scope, so extract values here, not objects."""
    document = QTextDocument()
    document.setPlainText(text)
    highlighter = ConfigHighlighter(document, palette)
    highlighter.rehighlight()
    block = document.firstBlock()
    ranges = block.layout().formats()
    return [
        {
            "start": r.start,
            "length": r.length,
            "bold": r.format.fontWeight() >= 700,
            "italic": r.format.fontItalic(),
            "color": r.format.foreground().color().name(),
        }
        for r in ranges
    ]


def test_header_line_is_highlighted():
    formats = _first_line_formats("! Generated by ConfigGen v0.1.0 | ...")
    assert formats
    assert formats[0]["start"] == 0
    assert formats[0]["bold"] is True


def test_comment_line_is_italic_and_muted():
    formats = _first_line_formats("! just a comment")
    assert formats
    assert formats[0]["start"] == 0
    assert formats[0]["italic"] is True


def test_plain_command_line_has_no_whole_line_format():
    # A plain non-comment, non-header line shouldn't get the header/comment
    # treatment (it may still have partial formats for IPs/strings, but not
    # covering column 0 as a whole-line italic/bold block).
    formats = _first_line_formats("hostname web01")
    assert not any(f["start"] == 0 and (f["bold"] or f["italic"]) for f in formats)


def test_ipv4_address_gets_a_format():
    formats = _first_line_formats("address 10.20.30.5/24")
    assert any(f["start"] > 0 for f in formats)  # the IP match doesn't start at column 0


def test_set_palette_updates_colors_and_rehighlights():
    light_formats = _first_line_formats("! header with Generated by ConfigGen", LIGHT)
    dark_formats = _first_line_formats("! header with Generated by ConfigGen", DARK)
    assert light_formats[0]["color"] != dark_formats[0]["color"]
