from PySide6.QtGui import QTextDocument

from configgen.ui.highlight_rules import DEFAULT_RULES, HighlightRule, save_custom_rules
from configgen.ui.highlighters import ConfigHighlighter, JinjaHighlighter
from configgen.ui.theme import DARK, LIGHT


def _first_line_formats(text: str, palette=LIGHT) -> list[dict]:
    """Plain-Python snapshots of the first block's format ranges — the
    underlying QTextCharFormat objects don't survive the document/
    highlighter going out of scope, so extract values here, not objects."""
    document = QTextDocument()
    document.setPlainText(text)
    highlighter = ConfigHighlighter(document, palette)
    highlighter.rehighlight()
    block = document.firstBlock()
    ranges = block.layout().formats()
    return [
        {
            "start": r.start,
            "length": r.length,
            "bold": r.format.fontWeight() >= 700,
            "italic": r.format.fontItalic(),
            "color": r.format.foreground().color().name(),
        }
        for r in ranges
    ]


def test_header_line_is_highlighted():
    formats = _first_line_formats("! Generated by ConfigGen v0.1.0 | ...")
    assert formats
    assert formats[0]["start"] == 0
    assert formats[0]["bold"] is True


def test_comment_line_is_italic_and_muted():
    formats = _first_line_formats("! just a comment")
    assert formats
    assert formats[0]["start"] == 0
    assert formats[0]["italic"] is True


def test_plain_command_line_has_no_whole_line_format():
    # A plain non-comment, non-header line shouldn't get the header/comment
    # treatment (it may still have partial formats for IPs/strings, but not
    # covering column 0 as a whole-line italic/bold block).
    formats = _first_line_formats("hostname web01")
    assert not any(f["start"] == 0 and (f["bold"] or f["italic"]) for f in formats)


def test_ipv4_address_gets_a_format():
    formats = _first_line_formats("address 10.20.30.5/24")
    assert any(f["start"] > 0 for f in formats)  # the IP match doesn't start at column 0


def test_set_palette_updates_colors_and_rehighlights():
    light_formats = _first_line_formats("! header with Generated by ConfigGen", LIGHT)
    dark_formats = _first_line_formats("! header with Generated by ConfigGen", DARK)
    assert light_formats[0]["color"] != dark_formats[0]["color"]


def test_interface_keyword_is_highlighted_by_default(_isolated_qsettings):
    # Nothing saved yet in this isolated settings store, so the default
    # word rules (highlight_rules.DEFAULT_RULES) are what's in effect.
    formats = _first_line_formats("interface Vlan1")
    assert any(f["start"] == 0 and f["length"] == len("interface") and f["bold"] for f in formats)


def test_dangerous_command_is_highlighted_by_default(_isolated_qsettings):
    formats = _first_line_formats("no shutdown")
    assert any(f["start"] == 0 and f["length"] == 2 and f["bold"] for f in formats)


def test_removing_a_default_rule_stops_highlighting_it(_isolated_qsettings):
    save_custom_rules([r for r in DEFAULT_RULES if r.word != "no"])
    formats = _first_line_formats("no shutdown")
    assert not any(f["start"] == 0 and f["length"] == 2 for f in formats)


def test_bare_number_gets_the_warning_color():
    formats = _first_line_formats("vlan 100")
    assert any(
        f["start"] == 5 and f["length"] == 3 and f["color"] == LIGHT.warning for f in formats
    )


def test_custom_rule_applies_its_own_color(_isolated_qsettings):
    save_custom_rules([HighlightRule(word="vlan", color="#123456", bold=True)])
    formats = _first_line_formats("vlan 10")
    assert any(f["start"] == 0 and f["length"] == 4 and f["color"] == "#123456" for f in formats)


def _jinja_formats(text: str, palette=LIGHT) -> list[dict]:
    document = QTextDocument()
    document.setPlainText(text)
    highlighter = JinjaHighlighter(document, palette)
    highlighter.rehighlight()
    block = document.firstBlock()
    ranges = block.layout().formats()
    return [
        {
            "start": r.start,
            "length": r.length,
            "bold": r.format.fontWeight() >= 700,
            "color": r.format.foreground().color().name(),
        }
        for r in ranges
    ]


def test_jinja_keyword_only_highlighted_inside_a_tag():
    formats = _jinja_formats("if plain text {% if x %}")
    # The bare "if" at column 0 (outside any {{ }}/{% %}) must not get the
    # keyword format — only the "if" inside the {% %} tag should.
    keyword_color = LIGHT.syntax_keyword
    assert not any(f["start"] == 0 and f["color"] == keyword_color for f in formats)
    tag_start = "if plain text {% if x %}".index("if x")
    assert any(f["start"] == tag_start and f["color"] == keyword_color for f in formats)


def test_jinja_highlights_numbers_and_ips_in_literal_template_text():
    text = " ip address 10.0.0.1 255.255.255.0"
    formats = _jinja_formats(text)
    ip_start = text.index("10.0.0.1")
    assert any(
        f["start"] == ip_start and f["length"] == len("10.0.0.1") and f["color"] == LIGHT.warning
        for f in formats
    )


def test_jinja_default_word_rule_applies_to_literal_template_text(_isolated_qsettings):
    formats = _jinja_formats("interface Vlan1\n no shutdown")
    assert any(f["start"] == 0 and f["length"] == len("interface") for f in formats)
