"""Builds the Jinja environment and renders a schema's document(s).

StrictUndefined means an unset variable raises immediately instead of
rendering as an empty string — the template editor's "Check" (phase 12) and
`configgen check` both rely on that to catch mistakes before Generate.
"""

from __future__ import annotations

import logging
from collections.abc import Callable
from datetime import datetime
from pathlib import Path

from jinja2 import Environment, FileSystemLoader, StrictUndefined

from configgen.appinfo import APP_NAME, __version__
from configgen.core.schema import Schema

logger = logging.getLogger(__name__)


class RenderError(Exception):
    pass


def build_environment(
    templates_dir: Path | str,
    *,
    filters: dict[str, Callable] | None = None,
) -> Environment:
    env = Environment(
        loader=FileSystemLoader(str(templates_dir)),
        undefined=StrictUndefined,
        trim_blocks=True,
        lstrip_blocks=True,
    )
    if filters:
        env.filters.update(filters)
    return env


def header_comment(schema: Schema, *, username: str, timestamp: datetime) -> str:
    stamp = timestamp.strftime("%Y-%m-%d %H:%M:%S")
    return (
        f"{schema.comment_prefix} Generated by {APP_NAME} v{__version__} | "
        f"Template: {schema.id} v{schema.version} | {stamp} | User: {username}\n"
    )


def render_documents(
    schema: Schema,
    context: dict,
    *,
    templates_dir: Path | str,
    username: str = "unknown",
    timestamp: datetime | None = None,
    filters: dict[str, Callable] | None = None,
) -> dict[str, str]:
    """Renders every document declared by the schema (one, for a single
    `template:` schema) and returns `{doc_key: text}`, each prefixed with
    the generated-config header comment."""
    env = build_environment(templates_dir, filters=filters)
    timestamp = timestamp or datetime.now()
    rendered = {}
    for doc in schema.document_list():
        logger.info("rendering schema=%s doc=%s template=%s", schema.id, doc.key, doc.template)
        try:
            template = env.get_template(doc.template)
            body = template.render(**context)
        except Exception as exc:
            # Deliberately broad, not just jinja2.exceptions.TemplateError:
            # a bad custom filter/global raising its own exception mid-render
            # (a ValueError, a TypeError from unexpected input, ...) is NOT
            # wrapped by Jinja2 — it propagates straight out of .render() as
            # whatever raw type it is. Narrower handling here used to let
            # exactly that kind of bug through as an uncaught exception,
            # which a --windowed build has no console to show — the button
            # just silently did nothing.
            logger.exception(
                "render failed: schema=%s doc=%s template=%s", schema.id, doc.key, doc.template
            )
            raise RenderError(f"{doc.key}: {exc}") from exc
        rendered[doc.key] = header_comment(schema, username=username, timestamp=timestamp) + body
        logger.info(
            "rendered schema=%s doc=%s (%d chars)", schema.id, doc.key, len(rendered[doc.key])
        )
    return rendered
