"""Builds the Jinja environment and renders a schema's document(s).

StrictUndefined means an unset variable raises immediately instead of
rendering as an empty string — the template editor's "Check" (phase 12) and
`configgen check` both rely on that to catch mistakes before Generate.
"""

from __future__ import annotations

from collections.abc import Callable
from datetime import datetime
from pathlib import Path

from jinja2 import Environment, FileSystemLoader, StrictUndefined
from jinja2.exceptions import TemplateError

from configgen.appinfo import APP_NAME, __version__
from configgen.core.schema import Schema


class RenderError(Exception):
    pass


def build_environment(
    templates_dir: Path | str,
    *,
    filters: dict[str, Callable] | None = None,
) -> Environment:
    env = Environment(
        loader=FileSystemLoader(str(templates_dir)),
        undefined=StrictUndefined,
        trim_blocks=True,
        lstrip_blocks=True,
    )
    if filters:
        env.filters.update(filters)
    return env


def header_comment(schema: Schema, *, username: str, timestamp: datetime) -> str:
    stamp = timestamp.strftime("%Y-%m-%d %H:%M:%S")
    return (
        f"{schema.comment_prefix} Generated by {APP_NAME} v{__version__} | "
        f"Template: {schema.id} v{schema.version} | {stamp} | User: {username}\n"
    )


def render_documents(
    schema: Schema,
    context: dict,
    *,
    templates_dir: Path | str,
    username: str = "unknown",
    timestamp: datetime | None = None,
    filters: dict[str, Callable] | None = None,
) -> dict[str, str]:
    """Renders every document declared by the schema (one, for a single
    `template:` schema) and returns `{doc_key: text}`, each prefixed with
    the generated-config header comment."""
    env = build_environment(templates_dir, filters=filters)
    timestamp = timestamp or datetime.now()
    rendered = {}
    for doc in schema.document_list():
        try:
            template = env.get_template(doc.template)
            body = template.render(**context)
        except TemplateError as exc:
            raise RenderError(f"{doc.key}: {exc}") from exc
        rendered[doc.key] = header_comment(schema, username=username, timestamp=timestamp) + body
    return rendered
