"""Generated-config syntax highlighting (§15).

A rendered config can be IOS, JunOS, a shell script, or anything else a
template author writes — there's no single fixed grammar to target, so
this is a light, generic highlighter: the ConfigGen header line, comment
lines (`!`/`#`/`//`/`;`, whichever the schema's `comment_prefix` is, plus
the other conventional ones so a preview never looks unhighlighted just
because of which platform it's for), quoted strings, and IPv4 addresses.
"""

from __future__ import annotations

from PySide6.QtCore import QRegularExpression
from PySide6.QtGui import QColor, QSyntaxHighlighter, QTextCharFormat, QTextDocument

from configgen.ui.theme import Palette

_COMMENT_PREFIXES = ("!", "#", "//", ";")
_IPV4_RE = QRegularExpression(r"\b(?:\d{1,3}\.){3}\d{1,3}(?:/\d{1,2})?\b")
_STRING_RE = QRegularExpression(r"\"[^\"]*\"|'[^']*'")


def _format(color: str, *, bold: bool = False, italic: bool = False) -> QTextCharFormat:
    fmt = QTextCharFormat()
    fmt.setForeground(QColor(color))
    fmt.setFontWeight(700 if bold else 400)
    fmt.setFontItalic(italic)
    return fmt


class ConfigHighlighter(QSyntaxHighlighter):
    def __init__(self, document: QTextDocument, palette: Palette):
        super().__init__(document)
        self._palette = palette
        self._build_formats()

    def _build_formats(self) -> None:
        self._header_format = _format(self._palette.accent, bold=True)
        self._comment_format = _format(self._palette.text_muted, italic=True)
        self._string_format = _format(self._palette.success)
        self._ip_format = _format(self._palette.danger)

    def set_palette(self, palette: Palette) -> None:
        self._palette = palette
        self._build_formats()
        self.rehighlight()

    def highlightBlock(self, text: str) -> None:
        if "Generated by ConfigGen" in text:
            self.setFormat(0, len(text), self._header_format)
            return
        if text.lstrip().startswith(_COMMENT_PREFIXES):
            self.setFormat(0, len(text), self._comment_format)
            return

        for pattern, fmt in ((_STRING_RE, self._string_format), (_IPV4_RE, self._ip_format)):
            match_iter = pattern.globalMatch(text)
            while match_iter.hasNext():
                match = match_iter.next()
                self.setFormat(match.capturedStart(), match.capturedLength(), fmt)
