"""Generates packaging/version_info.txt (a Windows EXE version resource)
from configgen.appinfo — the same single source of truth the window title,
CLI --version, and About dialog already read from, so the exe's own
Properties > Details tab (File description, File version, Product name,
Copyright, ...) is never out of sync with what the app reports about
itself. Run once from the repo root: `python tools/make_version_info.py`.

Not part of the app's runtime import graph — this only ever runs manually,
ahead of a packaging build, to (re)produce packaging/version_info.txt,
which ConfigGen.spec's EXE(version=...) then embeds into the built exe.

The output file's odd syntax (a bare `VSVersionInfo(...)` expression, no
imports) isn't an arbitrary style choice — PyInstaller loads it by
literally `eval()`-ing the text against its own versioninfo module
namespace (see PyInstaller.utils.win32.versioninfo.
load_version_info_from_text_file), so VSVersionInfo/FixedFileInfo/
StringFileInfo/StringTable/StringStruct/VarFileInfo/VarStruct must appear
unqualified, exactly as PyInstaller's own `pyi-grab_version` tool emits
them.
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "src"))

from configgen.appinfo import APP_NAME, AUTHOR, DESCRIPTION, __version__  # noqa: E402


def version_tuple(version: str) -> tuple[int, int, int, int]:
    """FixedFileInfo wants a 4-int (major, minor, build, revision) tuple;
    __version__ is semantic (major.minor.patch) — pad the missing slot."""
    parts = [int(p) for p in version.split(".")]
    while len(parts) < 4:
        parts.append(0)
    return tuple(parts[:4])


_TEMPLATE = """\
# UTF-8
#
# Generated by tools/make_version_info.py from configgen.appinfo — do not
# edit by hand, it's overwritten on every packaging build.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={version!r},
    prodvers={version!r},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0),
  ),
  kids=[
    StringFileInfo(
      [
        StringTable(
          '040904B0',
          [StringStruct('CompanyName', {author!r}),
           StringStruct('FileDescription', {description!r}),
           StringStruct('FileVersion', {version_str!r}),
           StringStruct('InternalName', {app_name!r}),
           StringStruct('LegalCopyright', {copyright!r}),
           StringStruct('OriginalFilename', '{app_name}.exe'),
           StringStruct('ProductName', {app_name!r}),
           StringStruct('ProductVersion', {version_str!r})])
      ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""


def render(
    *,
    app_name: str = APP_NAME,
    version: str = __version__,
    author: str = AUTHOR,
    description: str = DESCRIPTION,
) -> str:
    return _TEMPLATE.format(
        version=version_tuple(version),
        version_str=version,
        author=author,
        description=description,
        copyright=f"Copyright (c) {author}",
        app_name=app_name,
    )


def main() -> int:
    out_path = REPO_ROOT / "packaging" / "version_info.txt"
    out_path.write_text(render(), encoding="utf-8")
    print(f"wrote {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
